apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdevops-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appdevops
  template:
    metadata:
      labels:
        app: appdevops
    spec:
      containers:
      - name: appdevops
        image: andrebom/appdevops
        ports:
        - containerPort: 5000
